# Site settings -----------------------------------
title: L'assembleuse
subtitle: Outiller la transition
email: bonjour@lassembleuse.fr
description: L'assembleuse, l'agence d'accompagnement numérique et coopératif des projets de la transition
url: "https://lassembleuse.netlify.com" # the base hostname & protocol for your site
# url: "https://www.lassembleuse.fr" # the base hostname & protocol for your site

# Social settings ------------------------------------
github_username: lassembleuse
# twitter_username: ZooletteDesBois

# Build settings --------------------------------------
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages
