# Site settings -----------------------------------
title: L'assembleuse
subtitle: Outiller la transition
email: bonjour@lassembleuse.fr
description: L'assembleuse, agence d'accompagnement numérique et coopératif de projets de la transition
# url: "https://lassembleuse.netlify.com/" # the base hostname & protocol for your site
url: "https://www.lassembleuse.fr" # the base hostname & protocol for your site

# Social settings ------------------------------------
github_username: lassembleuse
# twitter_username: ZooletteDesBois

# Build settings --------------------------------------
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages
  - _headers

# Collections -------------------------------------------

collections:
  projects:
    output: true
    permalink: /projets-realises/:path/
    title: Projets
    layout: project

defaults:
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Jekyl assets -------------------------------------------

assets:
  precompile: [
    default-picture.jpg,
    default-picture-sq.png,
    exceptional-regular.woff2,
    exceptional-regular.woff,
    Montserrat-Regular.ttf,
    Montserrat-Bold.ttf
  ]
  sources:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/videos
    - assets/javascript
    - assets/video
    - assets/image
    - assets/img
    - assets/js
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img/projects
    - _assets/img
    - _assets/js
    - css
    - fonts
    - images
    - videos
    - javascript
    - video
    - image
    - img
    - js